# Generated by Django 2.1.7 on 2020-06-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='images/%Y_%m_%d', verbose_name='学校logo')),
                ('name', models.CharField(max_length=30, verbose_name='学校名字')),
            ],
            options={
                'verbose_name': '学校管理',
                'verbose_name_plural': '学校管理',
                'db_table': 'ra_schools',
            },
        ),
    ]
