# Generated by Django 2.1.7 on 2020-06-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=30, verbose_name='用户密码')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='电子邮箱')),
                ('role', models.IntegerField(choices=[(1, '普通用户'), (2, '白银会员'), (3, '黄金会员'), (4, '白金会员'), (5, '钻石会员'), (6, '超级管理员')], default=1, verbose_name='用户角色')),
                ('avatar', models.ImageField(null=True, upload_to='images/user/avatars', verbose_name='头像')),
                ('logintimes', models.IntegerField(default=0, verbose_name='登录次数')),
                ('last_login_time', models.DateTimeField(auto_now=True)),
                ('mark', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户备注')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'ra_accounts',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='token')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_app01.Account', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户认证',
                'verbose_name_plural': '用户认证',
                'db_table': 'ra_user_token',
            },
        ),
    ]
