# Generated by Django 2.1.7 on 2020-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app01', '0002_account_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=40, verbose_name='用户密码'),
        ),
    ]
